# command: hugo server -D --bind=0.0.0.0 --baseURL=http://192.168.0.12:1313
baseURL: https://8bitsqu.id/
languageCode: en-gb
title: Aadi Desai
theme: Shell
enableEmoji: true
params: # Customise Guide: https://github.com/Yukuro/hugo-theme-shell/blob/master/docs/customize_terminal/customize_terminal.md
  description: "Aadi Desai's Portfolio"
  Terminal:
    scheme: "MonokaiDark" # Themes: https://mayccoll.github.io/Gogh/
    userName: "Aadi"
    pcName: "Spectre"
    workDir: "Documents"
    profile: "profile.md"
    ps1Delay: 0.5
    stdoutDelay: 10
    commandDelay: 50
    titleDelay: 0.5
    contentDelay: 0.5
    description: |
      Hi there
      I'm Aadi
      Welcome to my site
      You'll find social links and my blog below
  Tree:
    use: true
    folderName: "links"
    files:
      - - About Me
        - "https://8bit.omg.lol/"
      - - My /now Page
        - "https://8bit.omg.lol/now/"
      - - Mastodon (social.lol)
        - "https://social.lol/@8bit/"
      - - LinkedIn
        - "https://www.linkedin.com/in/aadidesai/"
      - - Peerlist
        - "https://peerlist.io/_aadi/"
      - - GitHub
        - "https://github.com/supleed2/"
      - - Keybase
        - "https://keybase.io/aadidesai/"
      - - Projects Blog
        - "https://projects.8bitsqu.id/"
      - - My CV (PDF)
        - "https://github.com/supleed2/supleed2/blob/19bcb6d8d4f3d343227468a4ee39452b2b731a2c/AadiDesaiCV.pdf"
